version: '3.7'

services:     
  database:
    image: "postgres"
    container_name: check-point-db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=123456"
      - "POSTGRES_DB=check_point"
    ports:
      - "5431:5432"
    volumes:
      - ./sql/employee.sql:/docker-entrypoint-initdb.d/employee.sql
      - ./sql/registerPoint.sql:/docker-entrypoint-initdb.d/registerPoint.sql
#  backend:
#    build:
#       context: .
#       dockerfile: Dockerfile
#    container_name: check-point
#    ports:
#       - "3000:3000"
#    depends_on:
#      - database
