version: '3.9'

services:     
  database:
    image: "postgres"
    container_name: check-point-db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=123456"
      - "POSTGRES_DB=check_point"
      - "TZ=America/Sao_Paulo"
    ports:
      - "5437:5432"
    volumes:
      - ./sql/employee.sql:/docker-entrypoint-initdb.d/employee.sql
      - ./sql/registerPoint.sql:/docker-entrypoint-initdb.d/registerPoint.sql
  backend:
    build:
       context: .
       dockerfile: ./Dockerfile
    ports:
       - "3001:3001"
volumes:
  pg-data: